version: '3.7'

networks:
  kong-net:
    driver: bridge

services:
  #######################################
  # Postgres: The database used by Kong
  #######################################
  kong-database:
    container_name: kong-database
    image: postgres:9.6
    restart: always
    networks:
      - kong-net
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 5s
      timeout: 5s
      retries: 5

  #######################################
  # Kong database migration
  #######################################
  kong-migration:
    container_name: kong-migrations
    image: kong:2.0.3 # specific stable version
    depends_on:
      - kong-database
    links:
      - kong-database
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
    command: ["./wait-for-postgres.sh", "kong migrations bootstrap -v"]
  # for upgrade
    # command: kong migrations up -v
    # command: kong migrations finish -v

  #######################################
  # Kong: The API Gateway
  #######################################
  kong:
    container_name: kong
    image: kong:2.0.3 # specific stable version
    networks:
      - kong-net
    depends_on:
      - kong-migration
      - kong-database
    user: root
    restart: always
    environment:
      - KONG_DATABASE=postgres # database engine
      - KONG_PG_HOST=kong-database
      - KONG_PROXY_LISTEN=0.0.0.0:80, 0.0.0.0:443 ssl http2
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_NGINX_HTTP_RESOLVER=8.8.8.8
      - KONG_NGINX_PROXY_LUA_SSL_TRUSTED_CERTIFICATE=/etc/ssl/certs/ca-certificates.crt

    # ERROR_LOG
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
    # ACCESS_LOG
      - KONG_PROXY_ACCESS_LOG=/dev/null # disable access log improve little speed and don't save file on storage
      - KONG_ADMIN_ACCESS_LOG=/dev/null # disable access log

      - KONG_TRUSTED_IPS=0.0.0.0/0,::/0 # Real IP, X-Real-IP
      - KONG_REAL_IP_RECURSIVE=on # Real IP, X-Real-IP
    # PLUGINS
      - KONG_PLUGINS=bundled,hello
    # lua_package_path = /path/to/plugin1/?.lua;/path/to/plugin2/?.lua;;
      - KONG_LUA_PACKAGE_PATH=/etc/kong/plugins/hello/?.lua;;

      - KONG_LOG_LEVEL=debug # check PLUGINS load fail or success
    volumes:
      - ./plugins/hello:/etc/kong/plugins/hello
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:8001:8001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://kong:8001"]
      interval: 5s
      timeout: 2s
      retries: 15

  #######################################
  # Konga database prepare
  #######################################
  konga-database:
    container_name: konga_mongo
    image: mongo:4.4.0
    networks:
      - kong-net
    restart: on-failure
    depends_on:
      - kong
    volumes:
      - ./mongo_data:/data/db

  #######################################
  # Konga: Kong GUI
  #######################################
  konga:
    container_name: konga
    image: pantsel/konga:0.14.9
    restart: always
    networks:
      - kong-net
    environment:
      DB_ADAPTER: mongo
      DB_HOST: mongo
      NODE_ENV: production
    depends_on:
      - konga-database
    ports:
      - "127.0.0.1:1337:1337"
